baseurl = "http://jacobbridges.github.io/"
languageCode = "en-us"
title = "/dev/jacob"
builddrafts = true

[params]
	twitter = "https://twitter.com/codeweavr"
	profile = "https://pbs.twimg.com/profile_images/549048966071865344/ozB8Xi12_400x400.png"